### PR TITLE
Fix #25

### LINKED ISSUE #25: Python 3 - 503 Error: send HELO first
On Python 3 I've got the following error while trying to send any mail: `503 Error: send HELO first`.

I managed to investigate the source and it appears to be as follows.

You subclass `smtpd.SMTPChannel` and override the method `smtp_EHLO`.
In the CPython implementation of this method the instance variable `self.seen_greeting` is set and then, in the `smtp_RCPT` method, there is a check on that same variable ([relevant code here](https://hg.python.org/cpython/file/3.4/Lib/smtpd.py#l501)).
This check fails and trigger the error.

As far as I can see, there is no need to override the `smtp_EHLO` method.

### PR DESCRIPTION
**Pull request by aldur**
This should fix #25.
I tried both on Python 3.4 and 2.7 and it seems to work, but more tests are more than welcome.

### CODE REVIEW

**Comment by bcoe** [comment]
@aldur I'm not doing too much work in Python any more; it seems like you've tested this thoroughly, and I encourage you to merge at will :+1: I can also give you access to PyPi, if you would like to cut a new release.

**Comment by jowenn** [comment]
This among other things breaks Outlook 2016 connecting.

In 3.0.0 release( pypi) outlook at least gets across EHLO, but with GIT (with the ehlo override removed) master I get 502 Error "EHLO not implemented in the outlook transfer log. (python 2.7)

**Comment by aldur** [comment]
I see. Can you try, out of completeness, using Python 3? 

It seems that on CPython 2 there is no super implementation of that method (https://hg.python.org/cpython/file/2.7/Lib/smtpd.py#l192) and, instead, in Python 3 it's there (https://hg.python.org/cpython/file/3.5/Lib/smtpd.py#l410). 

I may revert the previous commit, but then we'd have again issue #25 against Python 3. 
I think we should do something as follows: if a super method exists, then call it. Otherwise, call our homemade implementation.

**Comment by bcoe** [comment]
@aldur should I push a new release to PyPi today, how are things looking?

**Comment by aldur** [comment]
Disclaimer: I haven't really looked into `secure-stmpd`, I'm just a little more than an external observer.

From what I see, there are a few issues, that should be pretty easy to fix.
Getting something robust enough to work with a lot of different clients may be done, but it's more difficult.

For a hypothetical new PyPi release, nothing changed much, I only merged this PR but things are far from working good (specifically regarding Python 2/3 integration).

I believe that, with time and help from the community, we may fix the issue and improve the compatibility; then there'll be time for a proper release.

**Comment by devsli** [comment]
It's broken on my Python 2.7 (unable to test with Python 3.5 due to #31)

Error when you try to start `example/ssl_client.py` with bundled `ssl_server.py`:
```
send: 'ehlo MacBook-Air-Leonid.local\r\n'
reply: '502 Error: command "EHLO" not implemented\r\n'
reply: retcode (502); Msg: Error: command "EHLO" not implemented
send: 'helo MacBook-Air-Leonid.local\r\n'
reply: '250 MacBook-Air-Leonid.local\r\n'
reply: retcode (250); Msg: MacBook-Air-Leonid.local
Traceback (most recent call last):
  File "examples/ssl_client.py", line 11, in <module>
    server.login('bcoe', 'foobar')
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 585, in login
    raise SMTPException("SMTP AUTH extension not supported by server.")
smtplib.SMTPException: SMTP AUTH extension not supported by server.
```

The first bad commit is 498e996da8abdbac69fb2c5b9697a89bc6efc369 so v3.0.0 is unaffected.

**Comment by bcoe** [comment]
@devsli would happily accept any patches you put forward, I would love to solve both your and @aldur's problems.

**Comment by devsli** [comment]
@bcoe thanks for fast response!
Unfortunately I'm not yet familiar with `smtpd` and `secure-smtpd` enough to fix it correct. Moreover I think @aldur has severe reason to remove `smtp_EHLO`. So I'll prefer to wait for his opinion.

**Comment by aldur** [comment]
@devsli from what I see, we have to develop a custom `smtp_EHLO` that refers to `super` implementation in Python 3 and restores the previous behaviour in Python 2 (that was broken in Python 3).

What do you guys think?

**Comment by devsli** [comment]
Sounds good :+1:

**Comment by grintor** [comment]
You can't delete the smtp_EHLO override. It's needed for auth. It just needs to be fixed for python3:

`	def smtp_EHLO(self, arg):
		if not arg:
			self.push('501 Syntax: HELO hostname')
			return
		if self.seen_greeting:
			self.push('503 Duplicate HELO/EHLO')
			return
		else:
			self.seen_greeting = arg
			self.push('250-%s Hello %s' %  (self.__fqdn, arg))
			self.push('250-AUTH LOGIN PLAIN')
			self.push('250 EHLO')`
This works in python3 but it needs some logic to go back to the python2 way when needed

**Pull request merged**
